apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-values
  namespace: flux-system
data:
  values.yaml: |
    pvc:
      storageClassName: local-path
      size: 20Gi
    service:
      type: ClusterIP
      port: 5000
    mountConfig: true
    configFiles:
      config.json: |-
        {
          "storage": { "rootDirectory": "/var/lib/registry" },
          "http": { "address": "0.0.0.0", "port": "5000" },
          "log": { "level": "info" },
          "extensions": {
            "search": { "enable": true },
            "ui": { "enable": true }
          }
        }
