apiVersion: ENC[AES256_GCM,data:RZI=,iv:kzI0Hdp9QCg4GUzMbmTpke4mghlcySOht6mJgEvFarc=,tag:cz6KOdaFD+bwYvL4zKo2QQ==,type:str]
data:
    admin-password: ENC[AES256_GCM,data:lL3kduXYvQGxpKbUV1BUyuzYqXu+J6GNt7wv06WRtT8+eGBY4P9I35LofvY=,iv:lqkY4VwulWWtaOryVkZRlIq6F/KwbxeT1ZhuoZCbgbs=,tag:DwLaGHlmNLKdpsmE0ytWLA==,type:str]
    admin-user: ENC[AES256_GCM,data:xjuktNpAD7A=,iv:wRitlY6s6IH9Pfdk85h0PnmHl3zqNsyNcehEtgDpwrs=,tag:vZf5hl35GrEq2MKI3Oac4g==,type:str]
kind: ENC[AES256_GCM,data:nBKzVHgp,iv:tqMq471UCAOdeXA3FoRXrCRo4lQJFJZhxO6aqHT8yXg=,tag:wzzTN2Nm6i9fYMNb72JRyQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2/CLhWGsW0/qOSuHAA==,iv:443NPZ4U3UIoza5wG0sjQMINQXmKlyGdI4QQABE84Bc=,tag:RfHDKjrkaSp4451qXtxJ2g==,type:str]
    namespace: ENC[AES256_GCM,data:RoBhCLntmA==,iv:MiFoAQz8pFygssJ55w80foUbwJQQ2TR/2i+rB6xwRkY=,tag:2kl4Wim0nw9byH/ubiU7Kg==,type:str]
sops:
    age:
        - recipient: age1zv0vrrtf3k30e7356qufsf4avfcdnq8c3z53dtkhszws48pcavuq5nt69g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVTdadDBuS0dmeG9NOVN2
            bVBlSGp4MjVPTVFHZ2w4amUzeXNjcDNsODE4ClMrMWVKWGpCOWFLQ0lCVTBRb3lq
            Q0Z4MHN1QXRFZ1dnWS9CanJ6T0c4U3MKLS0tIGJoQ29DVG42TWZZVzlxRVloWkFj
            UlpmVU9tS1ZXNGVUN3gybHg1S3hVZUkKhhfy8KwQu6YRv7TjeHZ2fuErVKMawvlY
            gJxz56iM1lweTIZcaK4o844CvIB7vSw5PeC7XQLOsv6L6Okn+RXVeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T14:22:58Z"
    mac: ENC[AES256_GCM,data:PUVBmPwjKRHcbgfku8C0h6ju1DGiO3JqdpqU/vDnx+FvHrC10+eFXcCHZL88Id24Wshh4LYkD9ktE875+Ujy5TAflod4CGWKehqGQHewLCG0EHWyByo8+DWQT1GEg3i/uLpQfaH36lDeczy/XGm7seNyeG/l/KUzil6NsYP3Ipg=,iv:9M/83+pn2/6GxcMm9LcoO2QeKkr3HsJWT99u785Zamw=,tag:Xdyrs02gREeFFuTwnRqYjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
