apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: logging
spec:
  interval: 1h
  chart:
    spec:
      chart: promtail
      version: "6.17.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 24h
  values:
    config:
      clients:
        - url: http://loki-gateway/loki/api/v1/push
