apiVersion: ENC[AES256_GCM,data:NTs=,iv:pn7vrMztNGuy5VQbntmSWvKLKYN6VoTAlviX8W/Te48=,tag:WCSAODx4SsIYLx+XqxgVKg==,type:str]
kind: ENC[AES256_GCM,data:PTmPWT7j,iv:NrGu1U8i2iIpG2PrpTYJrAzYgl5a/YKMXx93dXSpNQ0=,tag:Cs09QR9CJb8iHzZvRtkx2Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:68dexqvIaeLsbYWFcKBJ,iv:mAO4XCdguRtiPmO+nj014X9+p1eYqD13IQO+3ZkDJuM=,tag:wPkqsNNuXayviGtUyUs3kQ==,type:str]
    namespace: ENC[AES256_GCM,data:ApM+gkMTALQW7+IxkQ==,iv:DplTdm7OFUKUKg+BxbnUvecb89/oV676LAcZb03kPAk=,tag:143mGK5Ota88/d/I3OkwmA==,type:str]
type: ENC[AES256_GCM,data:2fvWnF1i,iv:7thjhr57oxVemmCShAbpJU+iuqVPzFNllUPmmUuN6EY=,tag:p3oEZ1iWPLeE2h3M6QQHpQ==,type:str]
stringData:
    anthropic-api-key: ENC[AES256_GCM,data:7BUWuCgelkDw9xrYtPRaGKRrBFaXsG2PspaourNT0skEzIHaBb2HwA6n/IcHhzuyDsCs3cLntTnaW7XoyKIGxH+0KxtkdzflSV/pRdVobv6tt7PfWfiF9GYpY7HXefP/ILu6hRQ4c8GxOV63,iv:35WCbJiU6HXEkXAONoKqs8qfmXfhSFsws5k+RByvs1c=,tag:v+gabGHAFrlP2+9ws1UYfA==,type:str]
    openai-api-key: ENC[AES256_GCM,data:QCpHiK8+jnyJa3gTyj43lx6I8w5y+0I/KjcpV3uUxlYBNK7/KylKpxCjSYS8TEQ6LmaV/5n1u/E72aS+VzO9yPE+gUcinWw35dwEjAyRuPvKk0UzlpbU6zji03Z+Ik0zbpzQOlVXh4jzdr0S5YieEsGuEYTQkNm2a6Zl15ePyN7S69/IPMTVo+s3I8TijJVGZMdMSMCFa3x2ZB3xtajToqOtX3k=,iv:lHxmJIA84lag1QH4yV7BpGlAUnF+Kshd7kZWWfoY3F8=,tag:DOsQh+CTHF3dKnudmpE1YA==,type:str]
    gemini-api-key: ENC[AES256_GCM,data:hzYPKiv9K9d7ULB2kf6haFej8silyGS/d4ofJYMUxEsk9zObof9g,iv:5eZ78uvZIrDa3cI30Bu5TFVdhTN5avThg5ICvf+fnis=,tag:Fikmj82z+Hv5Qz24Bh0vZg==,type:str]
    telegram-bot-token: ENC[AES256_GCM,data:YaFydZSWSLmT98U5+zAMMcx9YEdNcLGo8/qC50enBjR/tdwquDZAVrOXAbrvSg==,iv:cDMhWssR+2MLzcFNxlTERlkfQx6ewp1N2F8YOOq7+TM=,tag:MXsjvMMWwlNQhgkY21HwfQ==,type:str]
    gateway-password: ENC[AES256_GCM,data:6vsX+c34VJpmWo3ByzS/lTKSm4yUv3g/x2nAp3u6j8TjkGsU8bfp061yaJ3WUv9L,iv:25tibfunhbyRpFcGyFiBkxCce0LWtSe3KtK2EEcdD3g=,tag:k7W92ro4BDE726Yu8BjteQ==,type:str]
sops:
    age:
        - recipient: age1zv0vrrtf3k30e7356qufsf4avfcdnq8c3z53dtkhszws48pcavuq5nt69g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Y0dFemxncVRTL3JBSVQz
            c2lZaEN1ZER2azZPYnlRRlE1YnZxK3JMZDJRCjV3aUVENTJyeVFrNlFNOUk2QU1i
            QXAyZ1R6V3ZIMm0wU21Xcm1aaXhFYUEKLS0tIDRUZUZxRHNRYitJL3hmbDdINFFv
            MnFsZU14clZmNkVua1c0V1B1WFo3MzQKv+U9rpAAyv1YPufhIXBK8Cu7dtsDUBMI
            JkY6khDpvbBTD18p+SFqzLqlG9pvcS4E0/7xjOZ5SR17jRy1Nnza2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T20:39:04Z"
    mac: ENC[AES256_GCM,data:7HqXoiG5DUYjv8q3nqMM/TmhAz67MN6O25PWjC4AXj3ENvF5deQSe4GRy5X61IG0zoMc2lmKA59narvLyPCgqdtLBBmdA475cp1nTWjnXH/fRhGp+ft2yVrhIFLnqjWoecm00CxGYI0DDYcg2Uj/y4nzRsKdmG9ItdvUAOAN8z4=,iv:LNndEwcQz8MtSdr5Ein25v+o3N8F+1Ad7VUzlQ9vLhQ=,tag:LXHhnmBJjEHswclXyEDEpQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
