apiVersion: ENC[AES256_GCM,data:uTQ=,iv:NueWYFW+dJjm8k2gCScN4QtSbPXMkcpOepzlkVHVTbA=,tag:nuMQ4A2s2vBmVbS5PL6sfA==,type:str]
kind: ENC[AES256_GCM,data:Uf9uILIX,iv:q2U7y/4h84inwpKv2XS2mgwzqGYNBQsLmA34sMy/H0k=,tag:aQXsB6xBDEeKH5neJQhd4Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hnbM3LB76LWYp7dPUiNs,iv:wShejyCiPAkyVMTQgR4KmH6nlx2CgaVVzIjolv+sBaA=,tag:QdgbEfgxp/O4/BQheoDMhw==,type:str]
    namespace: ENC[AES256_GCM,data:11mGd8c4y/Oeb3cKUQ==,iv:gMxsguSX7Kj1aHfDES4DL/yyZV2nUSkVrKcisfZ2BmU=,tag:/j582lUG9Ea513ZHPpAvsQ==,type:str]
type: ENC[AES256_GCM,data:Ytv5Yf7s,iv:rI2l3dPto2DmgR4lXpy4G4QZn0yQHIJvQF4X2o0+2v8=,tag:UBOK3rC44ea4JxxdQrjhxQ==,type:str]
stringData:
    anthropic-api-key: ENC[AES256_GCM,data:zoq2yCKxdr0TMwuUphht8qMjOIapUFyDn4uW9Q1VN/ky8PVGKuUZAj3eDygs80oNBFqazgRTv1NFrO26HBl8gnH1HV1LuWas1mttWk7VRr51EppcdNg1mdMLMljKkv/YIfEbF8EcXAx76EhQ,iv:mMURDZSLvF96Bp8DiHrwAKUPum0kS7/hACo/iCvoIw8=,tag:O03ubyalZdFhH+P/U5qqag==,type:str]
    openai-api-key: ENC[AES256_GCM,data:GeNFdgbwOGU52xFCla9po54oFqtPJ2in3Fk6u7kcDZur1DzYMFTiSn1hD2bZ5Wu1urORY8sJIVD0+07ulu/nkyhOmRJATSiuzVD9wOSkzgEx9gju8Tycev8VXgCPPrIwZntW0O/iOjkg5uVDJotqrf6X+Sv8QHJa4SZAJKoFIGmWggWB31BxWJuSrhC0zCjQNCw5G7dc0Ze9gXqXR33JOiY/QKc=,iv:c0piJ6z4vJIxXwsxEw6G4Zanv1PUQT9knbU84sS7hsc=,tag:z8ycpo+j9M13btokBngItQ==,type:str]
    gemini-api-key: ENC[AES256_GCM,data:Q93ZmhkV+JZt9Ju4rWysUDg6Y4PCfLtx2kngc9NnPvmYITeHiquO,iv:plxclPGGK9RJ+XmJ0ekbVOJcj8midH6BwweN5rsC2ng=,tag:DQkYF61ZAibLyY8nDQ076Q==,type:str]
    telegram-bot-token: ENC[AES256_GCM,data:BrIHZu/lnwtvzBK2Rpde6xQCqJMRo2SdDfuEgbXQyZOfwfL9lw1/zT/NS1N2mA==,iv:Ao2S7yMxld6Yd8Ksyjwscwu/gpsKrYMDvlycVyfgvkI=,tag:SHjAe7YsbtKT/DK2S4lkwg==,type:str]
    gateway-password: ENC[AES256_GCM,data:GtNBqKpn4JXSsq4NR5cbATOOSB1uj31i3mQsPKsIhr0CkhhU8Q+njPqvsyTYtOAt,iv:XaVcmjHhaYHmdKJr4HDCQM+VSJ9x9MClf1NQPO+LNmU=,tag:NVtb2GT8SxJTUmxWmY01sQ==,type:str]
sops:
    age:
        - recipient: age1zv0vrrtf3k30e7356qufsf4avfcdnq8c3z53dtkhszws48pcavuq5nt69g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bWhoZklwYlV2bi9MK1h6
            UDF3RVlDNll0cW04T1RqQWhOSDcrSi8yZlRvCnR5UEFDZHpwR1N6bEFiL1UrZ3Br
            WTRXQThGK3E2SlMwRDhCR3oyVjN0NVkKLS0tIHpCa3phKzlta3NOYmd6U0NPdlFy
            bjVUQWk3V1lwaEoyK2xLN2sydDdMKzAKnuVX8m5eRBQcW8qVjEjWQ+4cHdUG8gN+
            vGux/NqrkLD6y/FmslaWR8SSmSh4hLeq6xi23Z1z1flazbM6L0zmiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T00:05:54Z"
    mac: ENC[AES256_GCM,data:QUNHbVRWafi+eY52dAP3CazvszWVbkgzdQ5Y0SME8V2VVxrru5jhqgHtL651ersUkPpG4pPAkuBoAGpPBlIxSF7Gc+dSdJNCiiGHtpFqfr5Qf7Rnwl20iDgwSFJz5OdQVikWgfvNtO9XUwdms7EDxX1RWKe2b3wC93sXQl6OOQ4=,iv:MWp75oVE7vsqR9X6oFjZEFbInN2j012tK1/iEbpAsTg=,tag:PUbu59eH0jxl+vVl2vj08w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
