apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-values
  namespace: flux-system
data:
  values.yaml: |
    ollama:
      gpu:
        enabled: true
        type: 'amd'
        number: 1
      models:
        pull:
          - dolphin3:8b-llama3.1-q4_K_M
          - mxbai-embed-large:v1
    extraEnv:
      - name: HSA_OVERRIDE_GFX_VERSION
        value: "10.3.0"
      - name: GPU_MAX_ALLOC_PERCENT
        value: "92"
      - name: GPU_MAX_HEAP_SIZE
        value: "92"
      - name: OLLAMA_MAX_LOADED_MODELS
        value: "1"
      - name: OLLAMA_NUM_PARALLEL
        value: "1"
      - name: OLLAMA_MAX_QUEUE
        value: "32"
      - name: OLLAMA_CONTEXT_LENGTH
        value: "8192"
      - name: OLLAMA_KEEP_ALIVE
        value: "2m"
      - name: OLLAMA_FLASH_ATTENTION
        value: "0"
      - name: OLLAMA_KV_CACHE_TYPE
        value: "q8_0"
      - name: OLLAMA_METRICS
        value: "true"
    nodeSelector:
      gpu.type: amd-rx6600xt
    tolerations:
      - key: gpu
        operator: Exists
        effect: NoSchedule
    resources:
      requests:
        cpu: 2000m
        memory: 2Gi
      limits:
        cpu: 8000m
        memory: 4Gi
    persistentVolume:
      enabled: true
      size: 20Gi
      storageClass: local-path
      accessModes:
        - ReadWriteOnce
    service:
      type: LoadBalancer
      port: 11434