apiVersion: ENC[AES256_GCM,data:W+M=,iv:JF4IKg2Qx5+HUweoHVFWAq1lrK3CDVRtpshTcwDzzeA=,tag:dWjDmKm0yJYbeFUo+QluAg==,type:str]
data:
    credentials.json: ENC[AES256_GCM,data:R8+afHIrBsbKkjPCcEP6P1z4lLT16TEGO2GnGdLRLsKUeV/er544d7vTCQar2nk7ga1w6AvnGWnCmXPTcPL6kZLxFEuq9eNqoubUQQabLVJMymNxBXWoM9gp3FX11FjMvvdY/TgAIIz0d2kZROSCCsJA6Pzi4DN2y5ztlu/MJ5i/7zWuVuaj/oqFnIgnWlAUo88U6tmBzKCJsT6nXvWhIh0IkTZbDPlXAVxQmM7Hpr3K6P3T+RHgkZKFbrdccj0qJIYEg6SaFXgYdxKFrACUFzZgVz+zRV9Eb7ZA9mIEXVQwMDQ1yPgeSWzSikA=,iv:odfoSR3nqSYL1oUW/dN2lGmyqyOKvYnfcJ7NS0mYUhY=,tag:AEW45zHHOuop1m8g0yTL5g==,type:str]
kind: ENC[AES256_GCM,data:AbilCU5I,iv:M9Oq/SnVPmTrWW5GuMTxSdYLsLDpcnEp0l1+eJYO+/A=,tag:eksAdFICaQJySZOcvcIFRA==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:U2VEmfSuWNDSxFHkQEqVEbbE,iv:2tICqQ0er+p3JSU8Z/fW/1E02XX7gKUybq77MqZJt1Y=,tag:ukPJPBRwdx6LnjRiD9LyFQ==,type:str]
    namespace: ENC[AES256_GCM,data:0telJgAquhbGO7g=,iv:Q2LRzayLfFE/7krBktStaaV7pM4U/lTaHBV569GScqI=,tag:6OAJVxQV1BetlrPMewLpnA==,type:str]
sops:
    age:
        - recipient: age1zv0vrrtf3k30e7356qufsf4avfcdnq8c3z53dtkhszws48pcavuq5nt69g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVDdMWWdEVHpoZ3pGMlR1
            Rkh0enBYUmJiWWk0d2w1bkYvSjV1bE5VbUhrCmtRYlJIYlM4bE5RVURRZDN6eU8r
            dmFEWnFla2phajdwVlByT1hVSWdqZWcKLS0tIE1abmpubmVlUG50UTBvUTIzQ2pV
            blRSSEJ1U2p1ZUgzVXUxWUYyOGtLY00K0VQkHfPXSaqKi6vE3fR/Q5j1kKtebjoi
            apPUZP6KWkHZJxKjJAxsg9OVYvlmPvXiHUjAmmy7Xwsg8XKyUHy5Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T18:26:52Z"
    mac: ENC[AES256_GCM,data:fxWLVM5pqQxCa1Dehk/w84qdHVXvP7HBUOwOSiI/vmLxn/2XXaL88qu+h5EH1RDG6c3EdxtKf4Wyvh2g8Qm5uvO6PvL+9YW1i9U3r4skbo3V1nFqmFxLXCcZwBYYNNZEHE4PNetL71t9N9B2GvJQQuQLgO/GnXtQ8Pk84uXbPKo=,iv:nK7WIP6Wsuqle6py7K+D63fQu1pYWuNCebkf7QkjgPg=,tag:bXsxIm1cS1+prY2tvDB+MA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
