apiVersion: ENC[AES256_GCM,data:SZw=,iv:a8IKRt2Rq8yj5USKFlNWHXUexkPn/eSChuZ7K5Rg0Fs=,tag:AVIZJl4k8siu1iIi3X47cw==,type:str]
kind: ENC[AES256_GCM,data:51t5Gl0r,iv:7qNy9LkkxcmUpSIUdiJpjiz2juNzxNadIaxkz/+REHE=,tag:aY7QNqKiQeiBVUSiUDp1eQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rF+reO6VBRwBPFcEP7Lwx7+QIeav+2ax2g==,iv:7xIMZXqQe+fZEUghsv3m6Z/RXURyQEC8CiHTDBrkIwc=,tag:j7vJtQ7zCHaoUnrtt8KaxA==,type:str]
    namespace: ENC[AES256_GCM,data:IHfx/bo=,iv:t46bOI8sITjf8ecOHbQQHI4zkU+m0YP2yx69eRDHIa4=,tag:qsdeKbowVO+jmOCYxSBAVg==,type:str]
type: ENC[AES256_GCM,data:W2t/zU+4,iv:6Hx7u+Yab0zfyZPGTlD7ii3CPuWLIsxzdRoVUlP8rzY=,tag:APixxBQEYn6azYVm6lFfIA==,type:str]
stringData:
    WOODPECKER_GITHUB_CLIENT: ENC[AES256_GCM,data:KqRxYcN72lx2nLy9h9Td1DnD3C8=,iv:SY505RBDBCYMkEWiS82W/jEY0AbRaS9RCGglcgtckeo=,tag:uz+6zVRvHRbGiolOW7rKRw==,type:str]
    WOODPECKER_GITHUB_SECRET: ENC[AES256_GCM,data:yotz1baka3B3Yxb+T/Kjvlv33BAJQIBfIwQMdMLe8aiX/di9xk9KlA==,iv:ZvpYdhjghave4acChY3JmlA7WWTv6ECCxAmJURDWoDM=,tag:hMDa9focY+BnkC6Sd4sNQA==,type:str]
sops:
    age:
        - recipient: age1zv0vrrtf3k30e7356qufsf4avfcdnq8c3z53dtkhszws48pcavuq5nt69g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWVg3eU5YaUZmVnFTVE9o
            aklQSzVtNmlGaXhtY1pqVHhnNXpiY0VRSm1jCmdZYm43NzRBMldrVmlYQkpJTjZj
            ckg4aWpWNi8wczBoQUlzSjZuSmZwQ3MKLS0tIEF6WXhJZG01NXVSM0dXbnBvUW9x
            N2xsYmY5M09EWEY5ZWtheGRUWnJlZGMKceCIffybf+fkYaJzUWsex6TAq+wHbvq5
            s1GOROM2sYHdZ/LsncdbONTRw2NEOEGOrA/XiPBqHVAoJlydtkHVhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T00:09:52Z"
    mac: ENC[AES256_GCM,data:rMeWk03j2k3TpVyB4Was4PuU6do4gXerx4KcAWJd10eAWZtyxi5tFFoq989hXSy5kPV+RtV6kl4DKe4weef+Wbm6SM4/EZ6JBXSKMn9ZMyx4+kPl2tROmkQ/XzkrkRXFmVuAeP3+UKX6W6QADSxSg0ktcdAJfhNSE2/+M7nEDOg=,iv:DlOaO28TyYjci+Y2TNGMeXU6DQ1oq347nKaQebAm5cE=,tag:pdFvIW8qCCLceEyypGLBrA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
