apiVersion: ENC[AES256_GCM,data:SZw=,iv:a8IKRt2Rq8yj5USKFlNWHXUexkPn/eSChuZ7K5Rg0Fs=,tag:AVIZJl4k8siu1iIi3X47cw==,type:str]
kind: ENC[AES256_GCM,data:51t5Gl0r,iv:7qNy9LkkxcmUpSIUdiJpjiz2juNzxNadIaxkz/+REHE=,tag:aY7QNqKiQeiBVUSiUDp1eQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rF+reO6VBRwBPFcEP7Lwx7+QIeav+2ax2g==,iv:7xIMZXqQe+fZEUghsv3m6Z/RXURyQEC8CiHTDBrkIwc=,tag:j7vJtQ7zCHaoUnrtt8KaxA==,type:str]
    namespace: ENC[AES256_GCM,data:Toz2Cw==,iv:P3iOyS5mtainiFCpnKAH5ch42z42fGX5xjJT2TEpztc=,tag:sP90FFaNFhzAn9iUgxU6TQ==,type:str]
type: ENC[AES256_GCM,data:W2t/zU+4,iv:6Hx7u+Yab0zfyZPGTlD7ii3CPuWLIsxzdRoVUlP8rzY=,tag:APixxBQEYn6azYVm6lFfIA==,type:str]
stringData:
    WOODPECKER_GITHUB_CLIENT: ENC[AES256_GCM,data:KqRxYcN72lx2nLy9h9Td1DnD3C8=,iv:SY505RBDBCYMkEWiS82W/jEY0AbRaS9RCGglcgtckeo=,tag:uz+6zVRvHRbGiolOW7rKRw==,type:str]
    WOODPECKER_GITHUB_SECRET: ENC[AES256_GCM,data:yotz1baka3B3Yxb+T/Kjvlv33BAJQIBfIwQMdMLe8aiX/di9xk9KlA==,iv:ZvpYdhjghave4acChY3JmlA7WWTv6ECCxAmJURDWoDM=,tag:hMDa9focY+BnkC6Sd4sNQA==,type:str]
sops:
    age:
        - recipient: age1zv0vrrtf3k30e7356qufsf4avfcdnq8c3z53dtkhszws48pcavuq5nt69g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWVg3eU5YaUZmVnFTVE9o
            aklQSzVtNmlGaXhtY1pqVHhnNXpiY0VRSm1jCmdZYm43NzRBMldrVmlYQkpJTjZj
            ckg4aWpWNi8wczBoQUlzSjZuSmZwQ3MKLS0tIEF6WXhJZG01NXVSM0dXbnBvUW9x
            N2xsYmY5M09EWEY5ZWtheGRUWnJlZGMKceCIffybf+fkYaJzUWsex6TAq+wHbvq5
            s1GOROM2sYHdZ/LsncdbONTRw2NEOEGOrA/XiPBqHVAoJlydtkHVhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T23:57:05Z"
    mac: ENC[AES256_GCM,data:iIEdpjzAV8j6+R6acmnYMyeqXg2koOX7pgjFE8N5Oisy2izTURpwYnfNFLuknAVMIG+pZA08MNXWjLUB7tfnShSlpsOkcXMHyHEUdck4T826EuePe+M9/TyeUx4HPzw1T6UIU/FMtWzMHoWO7Iu/udqcikzmbRMGD2KRGavKFKc=,iv:d1BOiYcMJMG87LaVPVtLrLjA3dFjl6L5KiqU7HiD1Zc=,tag:x2OY5p8nu9bsSi5cFxW43g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
