apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
    - name: infrastructure-configs
  interval: 10m
  path: ./apps/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
