apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: flux-system
spec:
  chart:
    spec:
      chart: n8n
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: community-charts
      version: "1.16.29"
  interval: 30m
  targetNamespace: agentic
  storageNamespace: agentic
  valuesFrom:
    - kind: ConfigMap
      name: n8n-values
      valuesKey: values.yaml
    - kind: Secret
      name: n8n-secret-values
      valuesKey: values.yaml
